# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oCK57Nw4jr4kAfwuI1ZN3O15eueG587K
"""

import pandas as pd

df = pd.read_csv('spg.csv')

print("=== GÖREV 1: VERİ Ön İşleme ===")

satir_sayisi, sutun_sayisi = df.shape
print(f"Veri Setindeki Toplam Veri Sayısı (Satır): {satir_sayisi}")
print(f"Veri Setindeki Toplam Sütun Sayısı (Sütun): {sutun_sayisi}")

print("\n--- Veri Setindeki Sütunların İsimleri ---")
print(df.columns.tolist())

print("=== TEKRAR EDEN VE EKSİK VERİ ANALİZİ ===")

tekrar_edenler = df[df.duplicated(keep=False)]
tekrar_sayisi = df.duplicated().sum()

print(f"Veri setindeki tekrar eden satır sayısı: {tekrar_sayisi}\n")

if tekrar_sayisi > 0:
    print("Tekrar Eden Satırların Eşleşmeleri: ")
    gruplanmis = tekrar_edenler.groupby(list(df.columns))
    for _, grup in gruplanmis:
        normal_satirlar = [str(idx + 1) for idx in grup.index]
        print(f" -> Satır {' ve '.join(normal_satirlar)} birbiriyle tamamen aynı.")

    df = df.drop_duplicates()
    print("\n-> Tekrar eden satırlar temizlendi, verinin tekil hali bırakıldı.")
else:
    print("-> Veri setinde tekrar eden hiç satır yok.")

print("\n--- Sütunlardaki Eksik (Boş) Veri Sayıları ---")
eksik_veriler = df.isnull().sum()
print(eksik_veriler)

toplam_eksik = eksik_veriler.sum()
print(f"\nToplam eksik veri sayısı: {toplam_eksik}")

if toplam_eksik > 0:
    df = df.dropna()
    print("-> Eksik veri içeren satırlar temizlendi.")
else:
    print("-> Veri setinde hiçbir eksik/boş değer bulunmuyor.")

import numpy as np

muaf_sutunlar = ['total_precipitation_sfc', 'snowfall_amount_sfc', 'shortwave_radiation_backwards_sfc', 'generated_power_kw']

sayisal_sutunlar = df.select_dtypes(include=[np.number]).columns
toplam_aykiri_sayisi = 0

for col in sayisal_sutunlar:
    if col in muaf_sutunlar:
        continue

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    if IQR == 0:
        continue

    alt_sinir = Q1 - 1.5 * IQR
    ust_sinir = Q3 + 1.5 * IQR

    aykiri_sayisi = ((df[col] < alt_sinir) | (df[col] > ust_sinir)).sum()

    if aykiri_sayisi > 0:
        print(f"-> '{col}' sütununda {aykiri_sayisi} adet gerçek aykırı değer (uç değer) düzeltildi.")
        toplam_aykiri_sayisi += aykiri_sayisi

        df[col] = np.where(df[col] < alt_sinir, alt_sinir, df[col])
        df[col] = np.where(df[col] > ust_sinir, ust_sinir, df[col])

print(f"\n Toplam {toplam_aykiri_sayisi} adet gerçek aykırı değer temizlendi.")

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.tree import DecisionTreeRegressor

y = df['generated_power_kw']
X = df.drop(columns=['generated_power_kw'])

print(f"Orijinal Özellik Sayısı: {X.shape[1]}")

scaler = MinMaxScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)
print("-> Veriler Min-Max Scaling yöntemiyle [0, 1] arasına başarıyla normalize edildi.\n")

print("Yöntem 1: Korelasyon Katsayısı ile En İyi Özellikler")
korelasyonlar = X_scaled.apply(lambda col: y.corr(col)).abs().sort_values(ascending=False)
print("Elektrik üretimiyle en ilişkili ilk 5 sütun:")
print(korelasyonlar.head(5))
print("-" * 50)

print("Yöntem 2: SelectKBest (İstatistiki F-Skor) ile En İyi Özellikler")
selector = SelectKBest(score_func=f_regression, k=5)
selector.fit(X_scaled, y)
ham_f_skorlari = pd.Series(selector.scores_, index=X.columns)
normalize_f_skorlari = (ham_f_skorlari - ham_f_skorlari.min()) / (ham_f_skorlari.max() - ham_f_skorlari.min())
f_skorlari = normalize_f_skorlari.sort_values(ascending=False)

print("F-Skoruna göre en önemli ilk 5 sütun (0-1 Arası Normalize Edilmiş):")
print(f_skorlari.head(5))
print("-" * 50)
print("Yöntem 3: Karar Ağacı (Decision Tree) Öznitelik Önem Dereceleri")
dt_model = DecisionTreeRegressor(random_state=42)
dt_model.fit(X_scaled, y)
agac_skorlari = pd.Series(dt_model.feature_importances_, index=X.columns).sort_values(ascending=False)
print("Karar Ağacına göre en önemli ilk 5 sütun:")
print(agac_skorlari.head(5))
print("-" * 50)
en_iyi_ozellikler = list(agac_skorlari.head(5).index)

print(f"\n3 Farklı Yöntemin Analizi Sonucunda Seçilen Ortak En Kritik Özellikler:")
for i, feat in enumerate(en_iyi_ozellikler, 1):
    print(f" {i}. {feat}")

X_final = X_scaled[en_iyi_ozellikler]
print(f"\nVeri seti temizlendi. Özellik sayısı {X.shape[1]}'den {X_final.shape[1]}'e indirgendi.")

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import pandas as pd
import numpy as np

X_train, X_test, y_train, y_test = train_test_split(X_final, y, test_size=0.2, random_state=42)

print(f"Eğitim Veri Seti Boyutu: {X_train.shape[0]} satır")
print(f"Test Veri Seti Boyutu: {X_test.shape[0]} satır\n")

lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

dt_model = DecisionTreeRegressor(random_state=42, max_depth=5)
dt_model.fit(X_train, y_train)

knn_model = KNeighborsRegressor(n_neighbors=5)
knn_model.fit(X_train, y_train)

metrik_sonuclari = []
modeller = {
    "Lineer Regresyon": lr_model,
    "Karar Ağacı Regresörü": dt_model,
    "KNN Regresörü": knn_model
}

for isim, model in modeller.items():
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)

    r2_train = r2_score(y_train, train_pred)
    r2_test = r2_score(y_test, test_pred)

    mae_train = mean_absolute_error(y_train, train_pred)
    mae_test = mean_absolute_error(y_test, test_pred)

    rmse_train = np.sqrt(mean_squared_error(y_train, train_pred))
    rmse_test = np.sqrt(mean_squared_error(y_test, test_pred))

    metrik_sonuclari.append({
        "Model": isim,
        "Eğitim R2 (Başarı)": f"%{r2_train*100:.2f}",
        "Test R2 (Başarı)": f"%{r2_test*100:.2f}",
        "Eğitim MAE (Hata kW)": f"{mae_train:.2f}",
        "Test MAE (Hata kW)": f"{mae_test:.2f}",
        "Eğitim RMSE (Hata kW)": f"{rmse_train:.2f}",
        "Test RMSE (Hata kW)": f"{rmse_test:.2f}"
    })
df_performans = pd.DataFrame(metrik_sonuclari)
print("MODELLERİN EĞİTİM VE TEST PERFORMANS KARŞILAŞTIRMASI:")
display(df_performans)

print("\n" + "="*60)
print("EN UYGUN MODELİN SEÇİLMESİ VE GEREKÇESİ:")
df_performans['test_r2_numeric'] = df_performans['Test R2 (Başarı)'].str.replace('%','').astype(float)
en_iyi_row = df_performans.loc[df_performans['test_r2_numeric'].idxmax()]

print(f"Veri Seti için En Uygun Model: {en_iyi_row['Model']}")
print(f"Gerekçe: Test veri setinde en yüksek açıklayıcılık oranına ({en_iyi_row['Test R2 (Başarı)']}) "
      f"ve en düşük ortalama hataya ({en_iyi_row['Test MAE (Hata kW)']} kW) bu model ulaşmıştır.")
print("="*60)

import joblib
from sklearn.preprocessing import MinMaxScaler

print("=== CANLIYA ALMA İÇİN MODELLERİN KAYDEDİLMESİ ===")

# Streamlit uygulamasında sadece seçilen 5 özelliği gireceğimiz için,
# sadece bu 5 özelliğe özel bir MinMaxScaler eğitip kaydediyoruz.
scaler_streamlit = MinMaxScaler()
scaler_streamlit.fit(df[en_iyi_ozellikler]) # Orijinal (df) veriden 5 sütunu alıp fitliyoruz

# Dosyaları Colab'a kaydediyoruz (.pkl formatında)
joblib.dump(knn_model, 'knn_sampiyon_model.pkl')
joblib.dump(en_iyi_ozellikler, 'kullanilan_ozellikler.pkl')
joblib.dump(scaler_streamlit, 'minmax_scaler.pkl')

print("Harika! 'knn_sampiyon_model.pkl', 'kullanilan_ozellikler.pkl' ve 'minmax_scaler.pkl' dosyaları başarıyla oluşturuldu.")

!pip install shap
import shap
import matplotlib.pyplot as plt

print("=== GÖREV 4: KARA KUTU MODEL AÇIKLANABİLİRLİĞİ (SHAP) ===")

X_train_summary = shap.kmeans(X_train, 100)
explainer = shap.KernelExplainer(knn_model.predict, X_train_summary)

print("SHAP değerleri hesaplanıyor, bu işlem 1-2 dakika sürebilir, bekle aga...")
shap_values = explainer.shap_values(X_test.iloc[:100])

plt.figure(figsize=(10, 6))
shap.summary_plot(shap_values, X_test.iloc[:100], show=False)
plt.title("KNN Kara Kutu Açıklanabilirliği - Özellik Etki Dağılımı")
plt.tight_layout()
plt.show()

print("\nSHAP Kara Kutu analizi tamamlandı!")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import joblib
# import pandas as pd
# import numpy as np
# 
# st.set_page_config(page_title="GES Elektrik Üretim Tahmini", layout="centered")
# st.title("☀️ Güneş Enerjisi Santrali (GES) Güç Tahmin Sistemi")
# st.markdown("Hava durumu verilerini girerek üretilecek elektrik miktarını (kW) tahmin edin.")
# 
# @st.cache_resource
# def load_models():
#     # Modeli, özellikleri VE SCALER'ı yüklüyoruz
#     model = joblib.load('knn_sampiyon_model.pkl')
#     features = joblib.load('kullanilan_ozellikler.pkl')
#     scaler = joblib.load('minmax_scaler.pkl')
#     return model, features, scaler
# 
# model, selected_features, scaler = load_models()
# 
# feature_mapping = {
#     'shortwave_radiation_backwards_sfc': 'Kısa Dalga Güneş Radyasyonu',
#     'angle_of_incidence': 'Güneş Işığının Geliş Açısı',
#     'total_cloud_cover_sfc': 'Toplam Bulutluluk Oranı (0-100)',
#     'azimut': 'Azimut Açısı (Güneş Yönü)',
#     'zenit': 'Zenit Açısı (Tepe Açısı)'
# }
# 
# st.subheader("Hava Durumu Parametrelerini Girin")
# user_inputs = {}
# 
# # Sadece seçilen özelliklerin giriş kutularını oluştur
# for feature in selected_features:
#     display_name = feature_mapping.get(feature, feature)
#     user_inputs[feature] = st.number_input(f"{display_name} değerini girin:", value=0.0)
# 
# if st.button("Üretimi Tahmin Et"):
#     try:
#         # Kullanıcının girdiği verileri DataFrame'e çevir
#         input_data = pd.DataFrame([user_inputs])
# 
#         # KRİTİK NOKTA: Girilen ham veriyi 0-1 arasına scale et (Eğitimdeki gibi)
#         input_scaled = scaler.transform(input_data)
# 
#         # Tahmini yap (Model eksi bir değer üretmesin diye max(0) koyduk)
#         tahmin = model.predict(input_scaled)[0]
#         tahmin_sonuc = max(0, tahmin)
# 
#         st.success(f"Beklenen Elektrik Üretimi: {tahmin_sonuc:.2f} kW")
#     except Exception as e:
#         st.error(f"Hata oluştu: {e}")